-- here script sql to create table "maintenix" 


CREATE TABLE maintenix(
AC VARCHAR(100),
LOCATION VARCHAR(100),
PART_REQUEST VARCHAR(100),
PART_REQUEST_STATUS VARCHAR(100),
PRIORITY_CD VARCHAR(100),
PART_NO VARCHAR(100),
QTY_UNIT_CD VARCHAR(100),
PART_TYPE_CD VARCHAR(100),
PART_USE_CD VARCHAR(100),
INV_CLASS_CD VARCHAR(100),
TASK_BARCODE VARCHAR(100),
TASK_NAME VARCHAR(100),
TASK_STATUS VARCHAR(100),
WP_BARCODE VARCHAR(100),
WP_NAME VARCHAR(100),
WP_STATUS VARCHAR(100),
WORK_TYPE_CD VARCHAR(100),
REQ_QT DOUBLE,
REQUEST_CREATION VARCHAR(100),
TASK_CREATION VARCHAR(100),
CONSTRAINT U_request UNIQUE (`AC`, `TASK_BARCODE`, `PART_REQUEST`, `REQUEST_CREATION`)
);
